import Head from 'next/head'

const Layout = (props: any) => {
    /**
     * COMPONENT PROPS
     */
    const { children, title } = props

    return (
        <>
            <Head>
                <title>{title || 'Courses'}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            {children}
        </>
    )
}

export default Layout
